### PR TITLE
I just migrated the contributing guide from layer5 to meshery-osm

### PR DESCRIPTION
**Pull request by emmanuellar**
I hope what I did was what is actually expected
I looked through the code of conduct from the CONTRIBUTING.md file in the layer5 project and I migrated it to this project after editing some links.

### CODE REVIEW

**Comment by leecalcote** [comment]
@emmanuellar there's a small item that you'll want to look into - signing-off on your commit(s). To do so in this PR, simply execute the `git` commands described here - https://github.com/layer5io/meshery-osm/pull/17/checks?check_run_id=968636975

To do so implicit for all future commits, have a look at these instructions - https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#signing-off-on-commits-developer-certificate-of-origin

**Comment by emmanuellar** [comment]
I've done this.
Thanks

**Comment by leecalcote** [comment]
Yay, @emmanuellar 🎈

**Comment by emmanuellar** [comment]
Yaaaaay💃🏽💃🏽💃🏽
I'll go ahead and join the slack community now.

**Pull request merged**
