### PR TITLE
fix: migrate service from port 10010 to 10009

### LINKED ISSUE #44: Bug: Move the meshery-osm adapter to port 10009
**Description**

We have used port 10010 for osm and there is no 10009

**Expected Behavior**

Let's not skip a port number and use 10009 for meshery-osm

### PR DESCRIPTION
**Pull request by kushthedude**
Signed-off-by: Kush Trivedi <kushthedude@gmail.com>
fixed #44

### CODE REVIEW

**Comment by kumarabd** [comment]
@kushthedude we can't change this before changing port for smi tool. That is running on 10009

**Review by kumarabd — COMMENTED** [review]
Smi-tool port needs to be changed first

**Comment by kushthedude** [comment]
> @kushthedude we can't change this before changing port for smi tool. That is running on 10009

The tool runs on 10008 port
https://github.com/layer5io/learn-layer5/blob/e6e57eccb62101378afebfb6166b31c34715bc8f/smi-conformance/main.go#L16

**Comment by leecalcote** [comment]
Gents, FYI - https://meshery.layer5.io/docs/architecture

**Comment by leecalcote** [comment]
10009 is currently reserved for Tanzu SM. Given that it's in an alpha state, we can swap these ports, if you feel this is a better fit.

We do need to get the `Learn Layer5` port documented.

**Comment by kushthedude** [comment]
So are we expecting tanzu anytime soon?

**Comment by leecalcote** [comment]
> So are we expecting tanzu anytime soon?
> […](#)

Our roadmap has a few items in front of the Meshery Adapter for Tanzu Service Mesh, so no, it might be a couple months before we get to the adapter for Tanzu SM.

**Comment by kushthedude** [comment]
I suggest let's migrate osm to 10009 then, @kumarabd ?

**Comment by leecalcote** [comment]
Irrespective of this issue on OSM, let's move the SMI Conformance tool to either 10000 or to it's own unique, port. 

Also, we will want the reservation for Tanzu SM updated - https://github.com/layer5io/meshery-tanzu-sm/issues/26

**Review by leecalcote — APPROVED** [review]

**Comment by leecalcote** [comment]
Please create an issue in the `learn-layer5` repo to complete this reassignment.

**Comment by KarenEfereyan** [comment]
@kumarabd and @leecalcote where exactly is the learn-layer 5 repo? I need to see its port number so I can update the meshery  docs with it

**Comment by kumarabd** [comment]
@KarenEfereyan Here you go - https://github.com/layer5io/learn-layer5

**Comment by kumarabd** [comment]
> @kumarabd and @leecalcote where exactly is the learn-layer 5 repo? I need to see its port number so I can update the meshery docs with it

@KarenEfereyan  Here you go - https://github.com/layer5io/learn-layer5

**Comment by KarenEfereyan** [comment]
Thank you @kumarabd

**Pull request merged**
